config/routes.rb
Notification::Application.routes.draw do
  devise_for :users

  resources :users, :only => [:show] do
    member do
      post :set_courses_with_major
      put :set_role
      get :show_to_be_confirmed_teachers
      put :set_teacher
      put :set_student
    end
  end

  resources :notices

  namespace :administration do
    match 'manage' => 'home#index', :via => :get
    match 'initialize_datas' => 'home#initialize_datas', :via => :post
  end

  resources :departments do
    collection do
      get :get_majors
    end
  end

  resources :majors
  resources :courses

  resources :departments do
    resources :majors do
      resources :courses
    end
  end

  resources :questions do
    resources :answers
  end

  match '/search', :to => "search#index"
  post '/send_to_students', :to => 'home#mail_to_students'
  root :to => "home#index"
end

app/models/question.rb
class Question
  include Mongoid::Document
  include Mongoid::Timestamps

  field :title,       :type => String
  field :content,     :type => String
  field :click_rate, :type => Integer, :default => 0

  has_many :answers
  belongs_to :course
  belongs_to :user

  scope :sorted, desc(:updated_at)

  def self.hot_question
    self.desc("click_rate").limit(5).to_a
  end

  def self.search_questions query
    query.strip!
    unless query.empty?
      terms =  query.split.join('|')
      Question.where('$or' => [{:title => /#{terms}/i}, {:content => /#{terms}/i}])
    else
      []
    end
  end

  def incr_visitation
    self.click_rate += 1
    save
  end

  def teachers
    course.majors.inject([]){ |result, m| result |= m.users.select{ |u| u.is_teacher? }; result }
  end

  def notice_to_course_major_teacher
    notices = create_question_notice(self.user, teachers)
  end

  def create_question_notice sender, receivers
    notice_attr = { :notice_type => "question",
      :content => self.content,
      :ref_id => self.id
    }

    receivers.each do |recevier|
      notice = Notice.generate_notice notice_attr, sender, recevier
      notice.save
      recevier.add_new_notice(notice)
    end
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def create
    question = Question.create params[:question]
    user = User.find params[:question][:user]
    user.add_asked_questions question
    question.notice_to_course_major_teacher
    redirect_to :back
  end

  def show
    @question = Question.find params[:id]
    @question.incr_visitation
    @answers = @question.answers
    @departments = Department.all
  end

  def index
    user = User.find params[:user_id]
    @questions = user.lastest_question_of_my_courses
  end

  def destroy
    question = Question.find params[:id]
    question.destroy
    redirect_to root_path
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_question.html.erb
<li class="question" id="<%= question.id %>">
<img src="<%= question.user.try :avatar %>" alt="">
<div class="question-section">
  <div class="question-title">
    <%= link_to question.title,question_path(question)  %>
  </div>
  <div class="question-details">
    <% if question.course %>
      <%= question.course.name %>  •  <%= question.user.name %>  •  <%= question.updated_at.strftime("%Y-%m-%d %H:%M")%>   <% if question.answers.last %>•  最后回复来自<%= question.answers.last.question.user.name %> <% end %>
    <% end %>
		</div>
	</div>
  <% if current_user.is_admin? %>
    <div class="remove-question">
      <%= link_to "删除", question_path(question), :method => "DELETE"%>
    </div>
  <% end %>
	<div class="question-has-answer">
		<span class="badge"><%= question.answers.count %></span>
	</div>
</li>

app/views/questions/show.html.erb
<div class="container">
  <div class="span8">
    <div class="span8">
      <div class="single-question span7">
        <div class="question-header span7">
          <div class="question-left-header span5">
            <div class="question-parent">

            </div>
            <div class="question-title">
              <%= @question.title %>
            </div>
            <div class="question-details">
              <%= @question.content %>
            </div>
          </div>
          <div class="question-right-avatar span1">
            <img src="<%= @question.user.avatar %>" alt="">
          </div>
        </div>

        <div class="question-body">
        </div>
        <div class="question-footer pull-right">
          最后更新时间: <%= @question.updated_at.strftime("%Y-%m-%d %H:%M")%>
        </div>
      </div>
    </div>

    <div class="span8">
      <div class="answers span7">
        <%= render( :partial => 'answers/answer' , :collection => @answers )%>
      </div>
    </div>

    <% if current_user %>
      <div class="span8">
        <div class="question-add-answer span7">
          <%= simple_form_for [@question, @question.answers.build]  do |f| %>
            <input type='hidden' name='user_id' value='<%= current_user.id%>'/>
            <%= f.input :content , :as => :text ,:placeholder=>"请在这里描述您的回答" ,:input_html => { :class => 'span7' ,:rows=>"10"} %>
            <%= f.button :submit, "发布" , :class=>"btn btn-primary"%>
          <% end %>
        </div>
      </div>
    <%end %>
  </div>
  <%= render 'home/user_sidebar' %>
</div>