config/routes.rb
Notification::Application.routes.draw do
  devise_for :users

  resources :users, :only => [:show] do
    member do
      post :set_courses_with_major
      put :set_role
      get :show_to_be_confirmed_teachers
      put :set_teacher
      put :set_student
    end
  end

  resources :notices

  namespace :administration do
    match 'manage' => 'home#index', :via => :get
    match 'initialize_datas' => 'home#initialize_datas', :via => :post
  end

  resources :departments do
    collection do
      get :get_majors
    end
  end

  resources :majors
  resources :courses

  resources :departments do
    resources :majors do
      resources :courses
    end
  end

  resources :questions do
    resources :answers
  end

  match '/search', :to => "search#index"
  post '/send_to_students', :to => 'home#mail_to_students'
  root :to => "home#index"
end

app/controllers/administration/home_controller.rb
require "#{Rails.root}/lib/init_helper.rb"
class Administration::HomeController < ApplicationController
  before_filter :authenticate_admin!

  def index
    @to_be_teachers = User.where(:role => "to_be_teacher")
    @departments = Department.all
    @questions = Question.all
  end

  def initialize_datas
    ::InitHelper.run
    render :text => 'ok'
  end
end

app/controllers/home_controller.rb
#encoding: utf-8
class HomeController < ApplicationController

  def index
    @departments = Department.all
    if current_user
      @questions = current_user.lastest_question_of_my_courses
      @questions_notices = current_user.list_questions_notices
    else
      @questions = Question.desc(:updated_at)
    end

    if current_user.is_admin?
      @questions = Question.desc(:updated_at)
    end

    render :layout => false
    # @hot_courses = Course.hot_course
  end

  def mail_to_students
    flash[:success] = '发送成功！'
    ResourcesMailer.send_to_students(current_user, params[:resource][:subject], params[:resource][:content])
    redirect_to root_path
  end

end

app/helpers/home_helper.rb
module HomeHelper

  def option_tag value, content
    raw("<option value='#{value}'>#{content}</option>")
  end
end

app/views/home/_askModel.html.erb
<% if current_user %>
  <div class="modal hide fade" id="newQuestion" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
      <%= simple_form_for current_user.asked_questions.build  do |f| %>
        <input type="hidden" name="question[user]" value="<%= current_user.id.to_s %>">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <%= f.input :title , :placeholder=>"您的问题是什么?" %>
      </div>
      <div class="modal-body">
        <%= f.input :content , :as => :text ,:placeholder=>"请在这里描述您的问题" ,:input_html => { :class => 'span5' ,:rows=>"10"} %>
        <input type="hidden" name="question[course]" value="<%= @course.id.to_s %>">
      </div>
      <div class="modal-footer">

        <%= f.button :submit, "发布" , :class=>"btn btn-primary"%>
      </div>
    <% end %>
  </div>
<% end %>

app/views/home/_head.html.erb
<div class="navbar navbar-static-top" style="margin-bottom:20px;">
              <div class="navbar-inner">
                <div class="container">
                  <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                  </a>
                  <a class="brand" href="/">医学化学教学辅导互动平台</a>
                  <div class="nav-collapse">

                    <form class="navbar-search pull-right" action="/search">
                      <input type="text" class="search-query span2" placeholder="Search" name='q'/>
                    </form>
                    <ul class="nav pull-right">
                      <li class="divider-vertical">
                        <% if current_user && current_user.is_admin? %>
                          <%= link_to '管理页面', administration_manage_path %>
                        <% end %>
                      </li>
                      <li class="divider-vertical"></li>
                      <% if user_signed_in? %>
                        <li>
                        <a href="<%= notices_path %>">
                          <%if current_user.notices.unread.count > 0%>
                          <span class="badge badge-important"><%= current_user.notices.unread.count%></span></a></li>
                      <%else%>
                          <span class="badge badge-normal"><%= current_user.notices.unread.count%></span></a></li>
                      <%end%>
                      <% end -%>
                      <li class="dropdown pull-right">
                        <% if user_signed_in? %>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.name %> <b class="caret"></b></a>
                        <% else %>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
                        <% end -%>
                        <ul class="dropdown-menu">
                          <%= render 'devise/shared/navigation' %>
                        </ul>
                      </li>
                    </ul>
                  </div><!-- /.nav-collapse -->
                </div>
              </div><!-- /navbar-inner -->
            </div>

app/views/home/_questions_list.html.erb
  <div class="span8 questions-list">
     <ul class="nav nav-tabs nav-stacked">
         <%= render( :partial => 'questions/question' , :collection => @questions )%>
     </ul>
  </div>

app/views/home/_user_sidebar.html.erb
<div class="span3 right-sidebar">
  <ul class="nav nav-tabs nav-stacked">


    <% if user_signed_in? && current_user.is_student? %>
      <li></li>
    <table class="table table-bordered table-striped">
      <thead>
        <td>
          <%= image_tag current_user.avatar , :class=>"user-avatar"%>
          <a href="">  <%= current_user.name  %></a>
        </td>
      </thead>
      <tbody>
      <tr>
        <td>
          <span class="label label-warning">Asked: <%= current_user.asked_questions.count%></span>
        </td>

      </tr>
      <tr>
        <td>
          <span class="label label-success">Answers:  <%= current_user.answers.count%></span>
        </td>
      </tr>

      <!-- For user major -->

      <% if current_user.major %>
        <tr>
        <td>
          <span class="label label-inverse">专业: <%= current_user.major.name%></span>
        </td>

      </tr>

    <% end -%>
      <!-- For user department -->

      <tr>
        <td>
          <span class="label label-inverse">所属院系: <%= current_user.try(:department).try(:name)%></span>
        </td>
      </tr>

      <% if @show %>
        <tr>
          <td><a href="#newQuestion" data-toggle="modal"><button class="btn btn-primary" type="button">Ask </button></a></td>
        </tr>
      <%end%>
      </tbody>
    </table>

    <table class="table table-bordered table-striped">
      <thead>
        <td>
          <b>课程</b>
        </td>
      </thead>
      <tbody>
      <% if user_signed_in? %>
        <% current_user.courses.each do |c| %>
        <tr>
        <td>
          <%= link_to c.name, course_path(c) %>
        </td>
      </tr>
    <% end -%>
      </tbody>
    <% end -%>
    </table>

    <table class="table table-bordered table-striped">
      <thead>
        <td>
          <b>专业</b>
        </td>
      </thead>
      <tbody>
      <% if user_signed_in? && current_user.department && current_user.department.majors %>
        <% current_user.department.majors.each do |c| %>

        <tr>
        <td>
          <%= link_to c.name, major_path(c) %>
        </td>
      </tr>
    <% end -%>
      </tbody>
    <% end -%>
    </table>

  <% end -%>
    <table class="table table-bordered table-striped">
      <thead>
        <td>
          <b>学院</b>
        </td>
      </thead>
      <tbody>
      <% @departments.each do |d| %>
        <tr>
        <td>
          <%= link_to d.name, department_path(d) %>
        </td>
      </tr>
    <% end -%>
      </tbody>
    </table>
  </ul>

  <% if current_user && current_user.is_teacher? %>
    <br>学生列表:
  <ul>
    <% current_user.get_my_students.each do |e|%>
      <li><%= e.email%> : <%= link_to e.name, e %></li>
  <%end%>
  </ul>

  <% end %>

</div>

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>医学化学教学辅导互动平台</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<%= render "home/head" %>
<body>

<div class="container">
  <%if user_signed_in? && current_user.is_teacher?%>

  <div class="container" >
    <%if flash[:success]%>
      <div class="alert alert-success">
        <span><%=flash[:success]%></span>
        <button type='button' class="close" data-dismiss='close'>x</button>
      </div>
    <%end%>

    <div style='width: 70%; float:left'>
      <%= render 'questions_list' %>

        <div>
          <h1>给学生发送邮件</h1>
        </div>

        <%=simple_form_for Resource.new, :url => send_to_students_path do |f| %>
          <%= f.input :subject, :label => '邮件标题'%>
          <%= f.input :content, :as => 'text', :label => '邮件内容'%>
          <%= f.submit '发送'%>
        <% end %>

    </div>

    <div style='float:right; width: 25%' >
      <%= render 'user_sidebar' %>
    </div>
  </div>
  <% else %>
  <% if !user_signed_in? %>
  <div class="container landing-page" >
    <h1 class='big'>医学化学教学辅导互动平台</h1>

    <div class="btn-container">
      <div class="my-btn"><h1><a href="/users/sign_in">进入</a></h1></div>
      <p class='info'>
        注册必须以实名、实际邮箱注册
      </p>
    </div>
  </div>
<% else %>
    <div class="container" >
    <%= render 'questions_list' %>
    <div style='float:right; width: 25%' >
      <%= render 'user_sidebar' %>
    </div>
  <% end %>
  <%end%>

</div>
</body>
</html>